(PDB-4855) Fix initialization of duplicate-pct metric
This was breaking the dashboard data query, and resulted in a blank
dashboard page.

While adding support for multiple write dbs we used a metric prefix to
distinguish between the two dbs metrics. We omitted providing the prefix
to this function, so the "value" of the metric was this string instead
of a duplication percentage.
```
"javax.management.RuntimeMBeanException: clojure.lang.ArityException: Wrong number of args (1) passed to: puppetlabs.puppetdb.utils.metrics/maybe-prefix-key"
```

This caused an error when we later tried to multiply this metric value.

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
at clojure.lang.Numbers.multiply(Numbers.java:173)
at puppetlabs.puppetdb.dashboard$fn_42532$get_dashboard_data42537$fn42538$iter4253942543$fn42544$fn_42545.invoke(dashboard.clj:162)
```