(PDB-2733) convergence: omit report duplicates
Skip any convergence test command sequences that include duplicate
:store-report commands (ignoring timestamps) because that's not an
expected situation, and as a practical matter, the duplicates will cause
a constraint violation

  ERROR:  duplicate key value violates unique constraint "reports_hash_expr_idx"

that will hang the convergence test until wait-for-processing times
out.  (Before wait-for-processing had a timeout it would just hang the
test indefinitely.)