(PDB-3952) init-db: don't open/return a connection pool
No one was using it, or closing it, which was causing the exceptions,
and it'd be better to just construct a pool from *db* if/when needed.

Sample exception:

  Jun 25, 2018 4:02:20 PM org.postgresql.Driver connect
  SEVERE: Connection error:
  org.postgresql.util.PSQLException: FATAL: database "pdb_test_593" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)