(PDB-1731) Add `clean all` step for FOSS el6 repos setup
This commit fixes an issue on el6 foss acceptance tests (non-aio) where
`yum install puppet -y` was getting:
```sh
el6-64-1 06:18:18$ yum install -y puppet
Loaded plugins: fastestmirror, presto
Determining fastest mirrors
Error: Cannot retrieve metalink for repository: epel. Please verify its
path and try again
```
This commit returns the `yum clean all -y` step before installing the
Puppet Labs repos so that we won't see these issues.