(PDB-4244) travis: brew update ruby to fix brew failures
Recently osx tests started failing like this during "brew install
bash":

  /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `initialize': no implicit conversion of nil into String (TypeError)
  from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `new'
  from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `<top (required)>'
  from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/Homebrew/Library/Homebrew/global.rb:25:in `<top (required)>'
  from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `require_relative'
  from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `<main>'

Some evidence suggested it might be resolved by updating ruby, but
an initial "brew install ruby" fails like this:

  error: HOMEBREW_LOGS was not exported!
  Please don't worry, you likely hit a bug auto-updating from an old version.
  Rerun your command, everything is up-to-date and fine now.

And indeed, running the command twice does seem to get the tests
working again.