(PDB-5712) client: restore puppet client for command posts
Use the new :post option to only post via the JDK client from
benchmark because we use the submit-* functions in both pdb and pdbext
tests, and those cause fips tests to fail with the current JDK client
configuration, e.g.:

  actual: java.lang.InternalError:
  java.security.NoSuchAlgorithmException: Unable to invoke creator for
  DEFAULT: Default key/trust managers unavailable

This should restore the puppet http client as of
6fc7da1e1ab124dc407999e5160d2d3c9905e59f (just before the switch to
the JDK client in dc2033c21d289b96dbfcb1aed3f93202391cb0ed) as the
default client for command submission.