(maint) Load OpenSSL library for lein gem commands
Without the `dev` profile, no OpenSSL library would be loaded, which
causes gem installation to fail with an error such as,

ERROR:  Loading command: install (NameError)
        cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass