(PDB-3952) Wait for any in-flight periodic tasks at shutdown
This addresses https://bugs.openjdk.java.net/browse/JDK-8176254 which
was causing jdbc exceptions like this:

  2018-09-07 16:33:02,000 ERROR [pool-4-thread-1] [p.p.c.services] Error while running package gc
  java.sql.SQLException: HikariDataSource HikariDataSource (PDBWritePool) has been closed.
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:79)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:298)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
        at puppetlabs.puppetdb.jdbc$with_transacted_connection_fn$fn__28840.invoke(jdbc.clj:481)
        at puppetlabs.puppetdb.jdbc$eval28814$retry_sql_STAR___28819$fn__28820$fn__28821.invoke(jdbc.clj:454)
        at puppetlabs.puppetdb.jdbc$eval28814$retry_sql_STAR___28819$fn__28820.invoke(jdbc.clj:453)
        at puppetlabs.puppetdb.jdbc$eval28814$retry_sql_STAR___28819.invoke(jdbc.clj:444)
        at puppetlabs.puppetdb.jdbc$with_transacted_connection_fn.invokeStatic(jdbc.clj:480)
        at puppetlabs.puppetdb.jdbc$with_transacted_connection_fn.invoke(jdbc.clj:469)
        at puppetlabs.puppetdb.cli.services$gc_packages_BANG_.invokeStatic(services.clj:174)

when the database connection was closed while a garbage
collection (for example) was still running.  Until we require jdk >=
10, work around it by coordinating the command and puppetdb service
stop methods with the relevant periodic operations.

The upgrade subcommand could regularly reproduce the problem on any
run after the first one (i.e. when there was no work to do).